### ISSUE TITLE
Clarification of ModemMessage timestamps

### ISSUE THREAD

**Issue by jaden-young** [HiberGlobal/api#5]
I'm wondering about the semantics of the timestamps in a `ModemMessage`.

https://github.com/HiberGlobal/api/blob/6d0e2ae0647bf23e664c0ef733e7b729e9db35ac/modem.proto#L174-L186

I can think of a few possible events that `sent_at` and `received_at` could represent:

1. Message is received by the Hiber cloud backend
2. Modem initiates transmission to a satellite
3. User application sends message to modem, but actual transmission to the satellite is delayed
4. Other?

I assume `received_at` maps to 1, but I'm not sure about `sent_at`.

Use case example:

User application sends a message to the Hiber modem every hour for 8 hours before the modem has a chance to transmit. Are the `sent_at` timestamps for those messages spaced by an hour, or are they all set to the time the modem began transmitting?

**Comment by wbouvy** [comment]
Sorry for the delay, didn't have alerts set up for issues :)
The `sent_at` time is set by the modem when the message is sent to the satellite, so option 2.

**Comment by jaden-young** [comment]
Thanks! That answers my question.
